// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu7z0G3IEZ5bIsk022bzW2LHhMpIWzjMA',
    appId: '1:649574617784:web:44330d5f1b3b2768695a4d',
    messagingSenderId: '649574617784',
    projectId: 'appjamoua',
    authDomain: 'appjamoua.firebaseapp.com',
    storageBucket: 'appjamoua.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABxVyy3jGPLBA49ppJ1K-ONqDmvzsyb3U',
    appId: '1:649574617784:android:941e40772e159f3c695a4d',
    messagingSenderId: '649574617784',
    projectId: 'appjamoua',
    storageBucket: 'appjamoua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvs7Qds-UnxOUUIkBt5u0s7ypk1ANQwmE',
    appId: '1:649574617784:ios:cabbe2e3f5b04ee9695a4d',
    messagingSenderId: '649574617784',
    projectId: 'appjamoua',
    storageBucket: 'appjamoua.appspot.com',
    iosClientId: '649574617784-04d9rh21ogev4p6r7dqi8itdei0eqcc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appJamOua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvs7Qds-UnxOUUIkBt5u0s7ypk1ANQwmE',
    appId: '1:649574617784:ios:cabbe2e3f5b04ee9695a4d',
    messagingSenderId: '649574617784',
    projectId: 'appjamoua',
    storageBucket: 'appjamoua.appspot.com',
    iosClientId: '649574617784-04d9rh21ogev4p6r7dqi8itdei0eqcc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appJamOua',
  );
}
